name: Build C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
      
      # Step 2: Configure CMake
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
        
      # Step 3: Build the project
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

